# Production Environment Configuration
# This file defines environment-specific settings for the production deployment

environment:
  name: production
  url: https://app.sabs-v2.com
  
# Protection rules
protection_rules:
  required_reviewers: 2
  prevent_self_review: true
  dismiss_stale_reviews: true
  require_code_owner_reviews: true
  require_linear_history: true
  required_status_checks:
    - code-analysis
    - testing
    - security-scan
    - performance
  
# Environment variables
variables:
  NODE_ENV: production
  LOG_LEVEL: warn
  ENABLE_SWAGGER: false
  RATE_LIMIT_ENABLED: true
  RATE_LIMIT_WINDOW_MS: 900000  # 15 minutes
  RATE_LIMIT_MAX_REQUESTS: 500  # More restrictive in production
  
# Deployment configuration
deployment:
  strategy: blue_green
  auto_deploy: false
  require_approval: true
  auto_promote: false
  canary_percentage: 10
  canary_duration: 300  # 5 minutes
  
# Resource limits
resources:
  memory: 4Gi
  cpu: 4
  min_instances: 2
  max_instances: 50
  
# Health checks
health_checks:
  enabled: true
  path: /health
  interval: 15s
  timeout: 5s
  healthy_threshold: 3
  unhealthy_threshold: 2
  
# Monitoring
monitoring:
  enabled: true
  alerts_enabled: true
  log_retention_days: 90
  metrics_enabled: true
  apm_enabled: true
  error_tracking_enabled: true
  
# Database configuration
database:
  instance_class: db-n1-standard-2
  storage_gb: 100
  backup_enabled: true
  backup_retention_days: 30
  point_in_time_recovery: true
  maintenance_window: "sun:02:00-sun:03:00"
  read_replicas: 2
  
# Security settings
security:
  ssl_enabled: true
  ssl_redirect: true
  hsts_enabled: true
  cors_enabled: true
  cors_origins: 
    - "https://admin.sabs-v2.com"
    - "https://app.sabs-v2.com"
  headers:
    strict_transport_security: true
    content_type_options: true
    frame_options: true
    xss_protection: true
    referrer_policy: true
    content_security_policy: true
    
# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 90
  cross_region_backup: true
  encryption_enabled: true
  
# Scaling configuration
scaling:
  auto_scaling_enabled: true
  target_cpu_utilization: 70
  target_memory_utilization: 80
  scale_up_cooldown: 300
  scale_down_cooldown: 600